### ISSUE TITLE
Pull to refresh

### ISSUE THREAD

**Issue by adin234** [manneohlund/smart-recycler-adapter#15]
Any plans on supporting pull to refresh?

**Comment by manneohlund** [comment]
Hi @adin234!
Not sure what you are referring to? Can you describe the use case? I will consider adding some features with additional dependencies as extending libraries.
Stay safe!

**Comment by adin234** [comment]
Hi @manneohlund !
Im referring to this behaviour.

![image](https://i.pinimg.com/originals/79/8c/0c/798c0cd60ce835b9de2016a89febade4.gif)

**Comment by manneohlund** [comment]
I'm gonna mark this as feature request and consider implementing it. The thing is that I don't see how this should be integrated in the library as an bundled component. This will probably be an extension library for the smart-recycler-adapter library due to potential extra dependencies.
Thanks for the feedback and stay tuned! 🙏

**Comment by ZiraiMode** [comment]
This behavior can be archived via SwipeToRefreshLayout from Google

**Comment by manneohlund** [comment]
Hmm considering the different spinner animation it might be added as a feature but yes, primary usage is the standard SwipeToRefeshLayout https://developer.android.com/training/swipe/add-swipe-interface.
