### ISSUE TITLE
How to get LinearLayoutManager to display horizontal

### ISSUE THREAD

**Issue by HenryChigbo** [manneohlund/smart-recycler-adapter#8]
Hello,
I added this to my RecyclerView
LinearLayoutManager linearLayoutManager = new LinearLayoutManager(this, LinearLayoutManager.HORIZONTAL, false);

But still, smart-recycler-adapter still displays it items vertical.
How can I make it display Linear horizontal.

Thanks for this library

**Comment by manneohlund** [comment]
Hi there, 
Sounds like you set the layout manager to the recycler view before you used the SmartAdapterBuilder. 
You can set the layout manager in the [SmartAdapterBuilder](https://github.com/manneohlund/smart-recycler-adapter/blob/master/smartadapter/src/main/java/smartadapter/SmartAdapterBuilder.java) and the builder will set it to the recycler view.
Or you can set it yourself after your SmartAdapterBuilder code. 

But I realized this is an issue and I will add an check in the builder so that you can do either way in the future.

Thanks for using this lib!

Ps: v3.0.0 will be released soon, got merged into master but jitpack was down for 48h so I couldn't verify some stuff. I'm currently migrating to maven/jcenter for v3.0.0.
Thanks for your patience!

**Comment by HenryChigbo** [comment]
Hello, I still have the same issue with version 3.0.0
When I write this

`SmartRecyclerAdapter
                .items(specialities)
                .map(TitleModel.class, TitleViewHolder.class)
                .map(ItemModel.class, SpecialityItemViewHolder.class)            
                .setLayoutManager(new LinearLayoutManager(this, LinearLayoutManager.HORIZONTAL, false))
                .into(specialityItem);`

It comes with empty items but when I remove the HORIZONTAL parameter in LinearLayoutManager the items will be align vertical.

What I need is to linear the items horizontally.
Is there anything wrong with the code sample above or is it from the library?

**Comment by manneohlund** [comment]
Hi,
I don't see any issue with your code example.
The `SmartAdapterBuilder` that is returned by `SmartRecyclerAdapter.items(...)` will automatically supply a vertical LinearLayoutManager if you don't set it in the builder as you did in your example.
So if you do `.setLayoutManager(new LinearLayoutManager(this, LinearLayoutManager.HORIZONTAL, false)` in the builder the items will be displayed horizontally.
See [sample code](https://github.com/manneohlund/smart-recycler-adapter/tree/master/sample/src/main/java/smartrecycleradapter/feature) classes for more examples.
